apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  labels:
    app: service-b
spec:
  replicas: {{ .Values.serviceB.replicas }}
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      serviceAccountName: ecr-access-sa
      containers:
        - name: service-b
          image: {{ .Values.serviceB.image }}
          ports:
            - containerPort: {{ .Values.serviceB.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-target-type: "ip"
spec:
  selector:
    app: service-b
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5001
  type: ClusterIP

