apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  labels:
    app: service-a
spec:
  replicas: {{ .Values.serviceA.replicas }}
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      serviceAccountName: ecr-access-sa
      containers:
        - name: service-a
          image: {{ .Values.serviceA.image }}
          ports:
            - containerPort: {{ .Values.serviceA.containerPort }}
          env:
            - name: SERVICE_B_URL
              value: "{{ .Values.serviceA.serviceBUrl }}"
---
apiVersion: v1
kind: Service
metadata:
  name: service-a
  labels:
    app: service-a
spec:
  selector:
    app: service-a
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.serviceA.containerPort }}
  type: ClusterIP
