apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  labels:
    app: service-a
spec:
  replicas: {{ .Values.serviceA.replicas }}
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      serviceAccountName: ecr-access-sa
      containers:
        - name: service-a
          image: {{ .Values.serviceA.image }}
          ports:
            - containerPort: {{ .Values.serviceA.containerPort }}
          env:
            - name: SERVICE_B_URL
              value: "{{ .Values.serviceA.serviceBUrl }}"
---
apiVersion: v1
kind: Service
metadata:
  name: service-a
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-name: "eks-lb"
spec:
  selector:
    app: service-a
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer

