apiVersion: apps/v1
kind: Deployment
metadata:
  name: mfe-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mfe-a
  template:
    metadata:
      labels:
        app: mfe-a
    spec:
      containers:
        - name: mfe-a
          image: 495599745704.dkr.ecr.ap-southeast-2.amazonaws.com/app1-mfe-a:{{ .Values.version | replace "." "-" }}
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mfe-a-{{ .Values.version | replace "." "-" }}
  labels:
    app: mfe-a-{{ .Values.version | replace "." "-" }}
spec:
  type: ClusterIP
  selector:
    app: mfe-a-{{ .Values.version | replace "." "-" }}
  ports:
    - name: http
      port: 80
      targetPort: 80
