apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: 495599745704.dkr.ecr.ap-southeast-2.amazonaws.com/web-app:{{ .Values.version | replace "." "-" }}
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mfe-a-{{ .Values.version | replace "." "-" }}
  labels:
    app: mfe-a-{{ .Values.version | replace "." "-" }}
spec:
  type: ClusterIP
  selector:
    app: mfe-a-{{ .Values.version | replace "." "-" }}
  ports:
    - name: http
      port: 80
      targetPort: 80
