serviceA:
  image: "495599745704.dkr.ecr.ap-southeast-2.amazonaws.com/app1-service-a:0.0.25"
  replicas: 1
  containerPort: 8080

  serviceBUrl: "http://service-b"

serviceB:
  image: "495599745704.dkr.ecr.ap-southeast-2.amazonaws.com/app1-service-b:0.0.2"
  replicas: 1
  containerPort: 8080
